export const MAFIA = 'Мафія';
export const MAFIA_DON = 'Дон Мафії';
export const DOCTOR = 'Лікар';
export const SHERIFF = 'Шериф';
export const BITCH = 'Шлюха';
export const TERRORIST = 'Терорист';
export const SECURITY = 'Тілоохоронець';
export const MANIAC = 'Маньяк';
export const PIECE = 'Мирний';
